-- =============================================
-- V6: Forecasting Functions (PL/pgSQL)
-- Adds stored procedures for health scoring,
-- anomaly detection, and overage prediction.
-- =============================================


-- -----------------------------------------------
-- 1. forecast_all_tenants()
--    Loops through all tenants in usage_snapshots,
--    computes a health_score (0-100) based on
--    recent api_calls_count trends, and upserts
--    into tenant_forecasts with a risk_level.
-- -----------------------------------------------
CREATE OR REPLACE FUNCTION forecast_all_tenants()
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_tenant_id UUID;
    v_health_score NUMERIC(5, 2);
    v_risk_level VARCHAR(20);
    v_recent_avg NUMERIC;
    v_older_avg NUMERIC;
    v_count INT := 0;
BEGIN
    FOR v_tenant_id IN
        SELECT DISTINCT tenant_id FROM usage_snapshots
    LOOP
        -- Recent 7-day average
        SELECT COALESCE(AVG(api_calls_count), 0)
        INTO v_recent_avg
        FROM usage_snapshots
        WHERE tenant_id = v_tenant_id
          AND snapshot_date >= CURRENT_DATE - INTERVAL '7 days';

        -- Previous 30-day average (excluding recent 7 days)
        SELECT COALESCE(AVG(api_calls_count), 0)
        INTO v_older_avg
        FROM usage_snapshots
        WHERE tenant_id = v_tenant_id
          AND snapshot_date >= CURRENT_DATE - INTERVAL '37 days'
          AND snapshot_date < CURRENT_DATE - INTERVAL '7 days';

        -- Compute health_score: if older_avg is 0, assume healthy
        IF v_older_avg = 0 THEN
            v_health_score := 75.00;
        ELSE
            -- Ratio of recent to older activity
            -- A growing or stable trend yields a high score
            -- A declining trend yields a low score
            v_health_score := LEAST(100.00, GREATEST(0.00,
                (v_recent_avg / v_older_avg) * 75.00
            ));
        END IF;

        -- Assign risk_level
        IF v_health_score >= 75 THEN
            v_risk_level := 'low';
        ELSIF v_health_score >= 50 THEN
            v_risk_level := 'medium';
        ELSIF v_health_score >= 25 THEN
            v_risk_level := 'high';
        ELSE
            v_risk_level := 'critical';
        END IF;

        -- Upsert into tenant_forecasts
        INSERT INTO tenant_forecasts (tenant_id, risk_level, health_score, forecast_date, notes)
        VALUES (
            v_tenant_id,
            v_risk_level,
            v_health_score,
            CURRENT_DATE,
            'Auto-generated by forecast_all_tenants(). Recent 7d avg: ' || ROUND(v_recent_avg, 1) ||
            ', Prior 30d avg: ' || ROUND(v_older_avg, 1)
        )
        ON CONFLICT (tenant_id, forecast_date)
            DO UPDATE SET
                risk_level   = EXCLUDED.risk_level,
                health_score = EXCLUDED.health_score,
                notes        = EXCLUDED.notes;

        v_count := v_count + 1;
    END LOOP;

    RETURN v_count;
END;
$$;


-- -----------------------------------------------
-- 2. detect_usage_anomalies()
--    Compares last 7 days of usage against the
--    30-day average per tenant. If any day exceeds
--    2x the average, an anomaly is flagged.
-- -----------------------------------------------
CREATE OR REPLACE FUNCTION detect_usage_anomalies()
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_tenant_id UUID;
    v_avg_calls NUMERIC;
    v_day_record RECORD;
    v_severity VARCHAR(20);
    v_count INT := 0;
BEGIN
    FOR v_tenant_id IN
        SELECT DISTINCT tenant_id FROM usage_snapshots
    LOOP
        -- 30-day average for this tenant
        SELECT COALESCE(AVG(api_calls_count), 0)
        INTO v_avg_calls
        FROM usage_snapshots
        WHERE tenant_id = v_tenant_id
          AND snapshot_date >= CURRENT_DATE - INTERVAL '30 days';

        -- Skip tenants with no meaningful baseline
        IF v_avg_calls = 0 THEN
            CONTINUE;
        END IF;

        -- Check each of the last 7 days
        FOR v_day_record IN
            SELECT snapshot_date, api_calls_count
            FROM usage_snapshots
            WHERE tenant_id = v_tenant_id
              AND snapshot_date >= CURRENT_DATE - INTERVAL '7 days'
        LOOP
            IF v_day_record.api_calls_count >= v_avg_calls * 3 THEN
                v_severity := 'high';
            ELSIF v_day_record.api_calls_count >= v_avg_calls * 2 THEN
                v_severity := 'medium';
            ELSE
                CONTINUE;  -- No anomaly for this day
            END IF;

            -- Only insert if this exact anomaly hasn't been recorded yet
            INSERT INTO anomalies (tenant_id, signal_type, detected_at, severity, description, resolved)
            SELECT
                v_tenant_id,
                'usage_spike',
                v_day_record.snapshot_date::TIMESTAMP,
                v_severity,
                'API calls on ' || v_day_record.snapshot_date || ': ' || v_day_record.api_calls_count ||
                ' (avg: ' || ROUND(v_avg_calls, 1) || ', ratio: ' ||
                ROUND(v_day_record.api_calls_count / v_avg_calls, 2) || 'x)',
                FALSE
            WHERE NOT EXISTS (
                SELECT 1 FROM anomalies a
                WHERE a.tenant_id = v_tenant_id
                  AND a.signal_type = 'usage_spike'
                  AND a.detected_at = v_day_record.snapshot_date::TIMESTAMP
            );

            IF FOUND THEN
                v_count := v_count + 1;
            END IF;
        END LOOP;
    END LOOP;

    RETURN v_count;
END;
$$;


-- -----------------------------------------------
-- 3. forecast_tenant_overage(p_tenant_id UUID)
--    Checks the tenant's current-month usage
--    against their billing plan's api_call_limit.
--    Returns a JSON object with overage details.
-- -----------------------------------------------
CREATE OR REPLACE FUNCTION forecast_tenant_overage(p_tenant_id UUID)
RETURNS JSON
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_usage INT;
    v_api_limit INT;
    v_overage_pct NUMERIC(8, 2);
    v_at_risk BOOLEAN;
BEGIN
    -- Sum API calls for the current month
    SELECT COALESCE(SUM(api_calls_count), 0)
    INTO v_current_usage
    FROM usage_snapshots
    WHERE tenant_id = p_tenant_id
      AND snapshot_date >= DATE_TRUNC('month', CURRENT_DATE)
      AND snapshot_date < DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month';

    -- Get the tenant's plan limit via invoices -> billing_plans
    SELECT COALESCE(bp.api_call_limit, 0)
    INTO v_api_limit
    FROM invoices i
    JOIN billing_plans bp ON bp.id = i.plan_id
    WHERE i.tenant_id = p_tenant_id
      AND i.status IN ('pending', 'paid')
    ORDER BY i.issued_at DESC
    LIMIT 1;

    -- Fallback if no plan found
    IF v_api_limit IS NULL OR v_api_limit = 0 THEN
        v_api_limit := 0;
        v_overage_pct := 0;
        v_at_risk := FALSE;
    ELSE
        v_overage_pct := ROUND((v_current_usage::NUMERIC / v_api_limit) * 100, 2);
        v_at_risk := v_overage_pct >= 80;
    END IF;

    RETURN json_build_object(
        'tenant_id', p_tenant_id,
        'current_usage', v_current_usage,
        'limit', v_api_limit,
        'overage_percentage', v_overage_pct,
        'at_risk', v_at_risk
    );
END;
$$;


-- Add unique constraint needed for upsert in forecast_all_tenants()
ALTER TABLE tenant_forecasts
    ADD CONSTRAINT unique_tenant_forecast_date UNIQUE (tenant_id, forecast_date);
