package com.cloudnest.backend.intelligence.controller;

import com.cloudnest.backend.entity.Anomaly;
import com.cloudnest.backend.entity.Intervention;
import com.cloudnest.backend.entity.TenantForecast;
import com.cloudnest.backend.intelligence.service.IntelligenceService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/intelligence")
@RequiredArgsConstructor
public class IntelligenceController {

    private final IntelligenceService intelligenceService;

    @GetMapping("/forecasts")
    public ResponseEntity<List<TenantForecast>> getAllForecasts() {
        return ResponseEntity.ok(intelligenceService.getAllForecasts());
    }

    @GetMapping("/forecasts/{tenantId}")
    public ResponseEntity<TenantForecast> getTenantForecast(@PathVariable UUID tenantId) {
        return intelligenceService.getTenantForecast(tenantId)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @GetMapping("/anomalies")
    public ResponseEntity<List<Anomaly>> getAnomalies() {
        return ResponseEntity.ok(intelligenceService.getAnomalies());
    }

    @GetMapping("/interventions/pending")
    public ResponseEntity<List<Intervention>> getPendingInterventions() {
        return ResponseEntity.ok(intelligenceService.getPendingInterventions());
    }

    @PutMapping("/interventions/{id}/resolve")
    public ResponseEntity<Intervention> resolveIntervention(@PathVariable UUID id) {
        return ResponseEntity.ok(intelligenceService.resolveIntervention(id));
    }

    @PostMapping("/run-diagnostics")
    public ResponseEntity<Map<String, String>> runDiagnostics() {
        String tenantIdStr = com.cloudnest.backend.multitenancy.TenantContext.getCurrentTenant();
        if (tenantIdStr == null) return ResponseEntity.badRequest().build();
        UUID tenantId = UUID.fromString(tenantIdStr);

        // Generate demo forecast
        TenantForecast forecast = TenantForecast.builder()
                .tenantId(tenantId)
                .healthScore(java.math.BigDecimal.valueOf((int)(Math.random() * 40) + 40))
                .riskLevel("medium")
                .forecastDate(java.time.LocalDate.now().plusDays(7))
                .notes("Generated by manual diagnostic run. Slight latency detected in API queries.")
                .build();
        intelligenceService.saveForecast(tenantId, forecast);

        // Generate anomaly
        Anomaly anomaly = Anomaly.builder()
                .tenantId(tenantId)
                .signalType("API Latency Spike")
                .severity("medium")
                .description("API endpoint /api/v1/orders experienced 400ms latency briefly.")
                .detectedAt(java.time.LocalDateTime.now())
                .resolved(false)
                .build();
        intelligenceService.saveAnomaly(anomaly);

        // Generate intervention
        Intervention intervention = Intervention.builder()
                .tenantId(tenantId)
                .anomalyId(anomaly.getId() != null ? anomaly.getId() : UUID.randomUUID())
                .actionTaken("Review Database Indexes")
                .status("pending")
                .createdAt(java.time.LocalDateTime.now())
                .build();
        intelligenceService.saveIntervention(intervention);

        return ResponseEntity.ok(Map.of("message", "Diagnostics completed"));
    }
}
